{"name": "Verify user logs in and navigates to Amazon website", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=51755): Max retries exceeded with url: /session/8deb81c218fd37367ed37b6119969d7f/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024475FD8FA0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "trace": "  File \"C:\\Users\\Spillibo\\PycharmProjects\\Project-1_Amazon_page\\venv\\lib\\site-packages\\behave\\runner.py\", line 545, in run_hook\n    self.hooks[name](context, *args)\n  File \"features\\environment.py\", line 23, in after_step\n    allure.attach(context.driver.get_screenshot_as_png(), name='screenshot_fail',\n  File \"C:\\Users\\Spillibo\\PycharmProjects\\Project-1_Amazon_page\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 836, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n  File \"C:\\Users\\Spillibo\\PycharmProjects\\Project-1_Amazon_page\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 847, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n  File \"C:\\Users\\Spillibo\\PycharmProjects\\Project-1_Amazon_page\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 343, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"C:\\Users\\Spillibo\\PycharmProjects\\Project-1_Amazon_page\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 291, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"C:\\Users\\Spillibo\\PycharmProjects\\Project-1_Amazon_page\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 312, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n  File \"C:\\Users\\Spillibo\\PycharmProjects\\Project-1_Amazon_page\\venv\\lib\\site-packages\\urllib3\\_request_methods.py\", line 110, in request\n    return self.request_encode_url(\n  File \"C:\\Users\\Spillibo\\PycharmProjects\\Project-1_Amazon_page\\venv\\lib\\site-packages\\urllib3\\_request_methods.py\", line 143, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n  File \"C:\\Users\\Spillibo\\PycharmProjects\\Project-1_Amazon_page\\venv\\lib\\site-packages\\urllib3\\poolmanager.py\", line 443, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"C:\\Users\\Spillibo\\PycharmProjects\\Project-1_Amazon_page\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 874, in urlopen\n    return self.urlopen(\n  File \"C:\\Users\\Spillibo\\PycharmProjects\\Project-1_Amazon_page\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 874, in urlopen\n    return self.urlopen(\n  File \"C:\\Users\\Spillibo\\PycharmProjects\\Project-1_Amazon_page\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 874, in urlopen\n    return self.urlopen(\n  File \"C:\\Users\\Spillibo\\PycharmProjects\\Project-1_Amazon_page\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 844, in urlopen\n    retries = retries.increment(\n  File \"C:\\Users\\Spillibo\\PycharmProjects\\Project-1_Amazon_page\\venv\\lib\\site-packages\\urllib3\\util\\retry.py\", line 515, in increment\n    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n"}, "steps": [{"name": "Given I am on the Amazon website", "status": "passed", "attachments": [{"name": "screenshot_pass", "source": "6669ea43-f646-4b5e-bb57-7a08dc1b91dd-attachment.png", "type": "image/png"}], "start": 1692686574603, "stop": 1692686588406}, {"name": "When I log in with my Amazon credentials read from excel_file", "status": "passed", "attachments": [{"name": "screenshot_pass", "source": "f5c992ad-b894-422a-85e9-19fdd1c51a21-attachment.png", "type": "image/png"}], "start": 1692686588406, "stop": 1692686594752}, {"name": "When I should be logged in successfully", "status": "passed", "attachments": [{"name": "screenshot_pass", "source": "5bef40b8-7300-46e6-a215-2ec1c6824f4d-attachment.png", "type": "image/png"}], "start": 1692686594753, "stop": 1692686595753}, {"name": "When I click on the All icon in the middle of the web page with the search box", "status": "passed", "attachments": [{"name": "screenshot_pass", "source": "6dfdd880-612b-4431-b01d-51346ac8ed66-attachment.png", "type": "image/png"}], "start": 1692686595753, "stop": 1692686596600}, {"name": "When I enter product name into the search box", "status": "passed", "attachments": [{"name": "screenshot_pass", "source": "2f1ae132-0620-4a79-812d-3c024c6b6062-attachment.png", "type": "image/png"}], "start": 1692686596600, "stop": 1692686603096}, {"name": "When I select required brand under the Brands section on the left scroll bar tab", "status": "passed", "attachments": [{"name": "screenshot_pass", "source": "6419bbc3-accc-4ff5-895c-2ec256c21bd9-attachment.png", "type": "image/png"}], "start": 1692686603096, "stop": 1692686606760}, {"name": "Then I select the third product from the results", "status": "passed", "attachments": [{"name": "screenshot_pass", "source": "7030e4b7-9955-4215-a46e-b5406e772ceb-attachment.png", "type": "image/png"}], "start": 1692686606760, "stop": 1692686614849}, {"name": "Then I ensure that the same product is not already added in the cart", "status": "passed", "attachments": [{"name": "screenshot_pass", "source": "98cf252f-68e9-42b1-96ea-1c8f1039d2db-attachment.png", "type": "image/png"}], "start": 1692686614849, "stop": 1692686618576}, {"name": "Then I click on \"Add to Cart\"", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=51755): Max retries exceeded with url: /session/8deb81c218fd37367ed37b6119969d7f/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024475FD8FA0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "trace": "  File \"C:\\Users\\Spillibo\\PycharmProjects\\Project-1_Amazon_page\\venv\\lib\\site-packages\\behave\\runner.py\", line 545, in run_hook\n    self.hooks[name](context, *args)\n  File \"features\\environment.py\", line 23, in after_step\n    allure.attach(context.driver.get_screenshot_as_png(), name='screenshot_fail',\n  File \"C:\\Users\\Spillibo\\PycharmProjects\\Project-1_Amazon_page\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 836, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n  File \"C:\\Users\\Spillibo\\PycharmProjects\\Project-1_Amazon_page\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 847, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n  File \"C:\\Users\\Spillibo\\PycharmProjects\\Project-1_Amazon_page\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 343, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"C:\\Users\\Spillibo\\PycharmProjects\\Project-1_Amazon_page\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 291, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"C:\\Users\\Spillibo\\PycharmProjects\\Project-1_Amazon_page\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 312, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n  File \"C:\\Users\\Spillibo\\PycharmProjects\\Project-1_Amazon_page\\venv\\lib\\site-packages\\urllib3\\_request_methods.py\", line 110, in request\n    return self.request_encode_url(\n  File \"C:\\Users\\Spillibo\\PycharmProjects\\Project-1_Amazon_page\\venv\\lib\\site-packages\\urllib3\\_request_methods.py\", line 143, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n  File \"C:\\Users\\Spillibo\\PycharmProjects\\Project-1_Amazon_page\\venv\\lib\\site-packages\\urllib3\\poolmanager.py\", line 443, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"C:\\Users\\Spillibo\\PycharmProjects\\Project-1_Amazon_page\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 874, in urlopen\n    return self.urlopen(\n  File \"C:\\Users\\Spillibo\\PycharmProjects\\Project-1_Amazon_page\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 874, in urlopen\n    return self.urlopen(\n  File \"C:\\Users\\Spillibo\\PycharmProjects\\Project-1_Amazon_page\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 874, in urlopen\n    return self.urlopen(\n  File \"C:\\Users\\Spillibo\\PycharmProjects\\Project-1_Amazon_page\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 844, in urlopen\n    retries = retries.increment(\n  File \"C:\\Users\\Spillibo\\PycharmProjects\\Project-1_Amazon_page\\venv\\lib\\site-packages\\urllib3\\util\\retry.py\", line 515, in increment\n    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n"}, "start": 1692686618577, "stop": 1692686660892}, {"name": "Then only a single product should be added to the cart", "status": "skipped", "start": 1692686660892, "stop": 1692686660892}, {"name": "Then I click on \"Proceed to Checkout\"", "status": "skipped", "start": 1692686660892, "stop": 1692686660892}, {"name": "And I should be taken to the checkout page for further steps in the purchase process", "status": "skipped", "start": 1692686660892, "stop": 1692686660892}], "start": 1692686574603, "stop": 1692686660892, "uuid": "8334a763-e03f-4116-b456-9896ed6281d3", "historyId": "670fe7bbd7472c63f78ee5c45f901c98", "fullName": "Verify boAT wireless headphone is added to the cart: Verify user logs in and navigates to Amazon website", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Verify boAT wireless headphone is added to the cart"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}